version: '3.4'
services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FRONTEND_SERVER_ADDR=unlockd-webclient:3000 
      ## the trailing slash is important here.  It means rewrite the URI to not include /api/
      - FLASK_SERVER_ADDR=backend:5000/
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - unlockd-backend
      - unlockd-webclient
  unlockd-backend:
    image: unlockd-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    #environment:
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - 5000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  unlockd-webclient:
    image: unlockd-webclient
    build:
      context: ./unlockd-webclient
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  mongo:
      image: mongo
      restart: always
      volumes:
        - './data:/data/db'
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      command: --quiet --logpath /dev/null 
  ## this isn't working for some reason
  #cron:
  #  build: ./dockerized-cron

#web:
#  environment:
#    - PYTHONUNBUFFERED=1