version: '3.4'

services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=flaskpythonlightningbackend:5000 
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - flaskpythonlightningbackend
  flaskpythonlightningbackend:
    image: flaskpythonlightningbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - hardcoded_ip="54.176.48.9"
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - 5000:5000
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      command: --quiet --logpath /dev/null 
#web:
#  environment:
#    - PYTHONUNBUFFERED=1